### ISSUE TITLE
[BUG] total.vizualize() failes on Getting Started with Dask

### ISSUE THREAD

**Issue by khcs** [rapidsai/notebooks#165]
Introduction to Dask
https://github.com/rapidsai/notebooks-extended/blob/master/beginner/basics/Getting_Started_with_Dask.ipynb

total.visualize() throws error:
`RuntimeError: Drawing dask graphs requires the 'graphviz' python library and the 'graphviz' system library to be installed.`

I had to execute the following commands to resolve this issue:
`conda install graphviz`
`conda install python-graphviz`

**Comment by dlymarg** [comment]
I had to execute the same commands in the following notebooks:

notebooks-extended/beginner/tutorials/03_Introduction_to_Dask.ipynb
notebooks-extended/beginner/tutorials/04_Introduction_to_Dask_using_cuDF_DataFrames.ipynb

After I implemented the commands, the graphics returned with boxes instead of text. However, when I ran the notebook khcs mentioned, the text displayed fine (perhaps it had something to do with being in a different session?). Here is an example of the issue I encountered with the graphics having text display as boxes:

https://community.atlassian.com/t5/Marketplace-Apps-Integrations/graphviz-text-showing-up-as-squares/qaq-p/85693

https://stackoverflow.com/questions/21587974/graphviz-plugin-in-confluence-showing-text-as-boxes

**Comment by taureandyernv** [comment]
fixed with https://github.com/rapidsai/notebooks-extended/pull/64
