### ISSUE TITLE
[BUG] AttributeError: module 'cudf' has not attribute '_gdf' (in advanced Dask with cuDF and XGBoost)

### ISSUE THREAD

**Issue by dlymarg** [rapidsai/notebooks#167]
This bug was found in:

/notebooks-extended/advanced/examples/Dask_with_cuDF_and_XGBoost.ipynb (NOTE: Problem also occurs in Dash_with_cuDF_and_XGBoost_from_Disk.ipynb)

When I try to run the second cell under the section "Use cuIO to Load GPU DataFrames using Dask," I get the following error:

`AttributeError: module 'cudf' has no attribute '_gdf'`

This error message is followed by a bunch of lines that seem to be causing the error. Consequently, I cannot execute most of the commands that follow that error message. If needed, I can paste the entire error message in this thread.

To be honest, I am not sure what the expected behavior is because there is no written explanation leading up to the cells that need to be executed. Any help would be appreciated. Thanks!

 - Environment location: Docker
 - Method of RAPIDS libraries install: Docker
   - `docker pull` & `docker run` commands used:
```
docker pull rapidsai/rapidsai:0.7-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
rapidsai/rapidsai:0.7-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7
```

**Comment by taureandyernv** [comment]
@dlymarg thanks for finding this bug, and sorry about the delay.  While this is in the wrong repo, we need to update this notebook as it uses `dask_delayed` and not `dask_cudf`.  RMM is becoming its own standalone repo, and even some the quick fixes, it doesn't pickle well.  I'm not sure how  critical the bug is for you, but please let me know if this is a blocking you for our prioritization and stand by for a PR with the solution!  

Thanks again!

**Comment by taureandyernv** [comment]
@dlymarg talked with the notebook creator and he has a similar, yet updated, notebook in the repo.  We'll be archiving this notebook and a few others.  Thanks again!
